import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst, NetworkFirst, NetworkOnly } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { ExpirationPlugin } from 'workbox-expiration';
import { BackgroundSyncPlugin } from 'workbox-background-sync';

// Background Sync Queue for offline data entry
const syncPlugin = new BackgroundSyncPlugin('manolog-sync-queue', {
  maxRetentionTime: 24 * 60, // Retry for up to 24 hours
});

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache common Google Fonts
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com' || url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({ maxEntries: 20, maxAgeSeconds: 60 * 60 * 24 * 365 }),
    ],
  })
);

// Cache static assets (images, etc)
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images',
    plugins: [
      new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 60 * 60 * 24 * 30 }),
    ],
  })
);

// Cache API responses for data that doesn't change frequently (e.g. settings)
// For journals/tracking, we might want NetworkFirst or manual sync
registerRoute(
  ({ url }) => url.pathname.includes('/api/'),
  new NetworkFirst({
    cacheName: 'api-cache',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  })
);

// SYNC WRITE REQUESTS (POST, PATCH, DELETE)
registerRoute(
  ({ url, request }) => 
    url.pathname.includes('/api/') && 
    (request.method === 'POST' || request.method === 'PATCH' || request.method === 'DELETE'),
  new NetworkOnly({
    plugins: [syncPlugin]
  })
);

// PUSH NOTIFICATION LISTENERS (Migrated from public/sw.js)
self.addEventListener("push", (event) => {
  const data = event.data ? event.data.json() : {};
  const title = data.title || "ManologAI Reminder";
  const options = {
    body: data.body || "It's time for your daily check-in!",
    icon: "/logo.png",
    badge: "/logo.png",
    vibrate: [200, 100, 200],
  };

  event.waitUntil(self.registration.showNotification(title, options));
});

self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  event.waitUntil(
    clients.matchAll({ type: "window" }).then((clientList) => {
      for (const client of clientList) {
        if (client.url === "/" && "focus" in client) return client.focus();
      }
      if (clients.openWindow) return clients.openWindow("/");
    })
  );
});

// Allow the service worker to take control of the page immediately
self.addEventListener('install', () => self.skipWaiting());
self.addEventListener('activate', (event) => event.waitUntil(clients.claim()));
